name: SugarPets
author: Mysurvival Network
author: SugarPocket
description: Simple Pets Plugin By BalAnce + Driesboy + Lifeboat
version: 4.0.0
main: pets\main
api: [1.0.0, 2.0.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2]
